[global]
error_file = /var/log/wesmexico_error.log
access_file = /var/log/wesmexico_access.log
db_sync_file = /var/log/wesmexico_sync.log

[server]
port=3023
host=0.0.0.0

[database]
host=localhost
#port=3306
db=wesmexico
user=wesmexico_rw
passwd=$WesMexico123.
init_command=SET time_zone = "+00:00"
#max_connections=4

[smtp]
server=mail.wesmexico.com
port=465
user=noreply@wesmexico.com
password=LKKfv813##

[asset]
path=/var/erp-wesmexico/resources/assets

[settings]
pdf-reports-host=pdf-reports.localhost.org
disable-replication=True
debug=1
